[project]
name = "voltage-control-env"
version = "1.1.0"
dependencies = [
    "simbench >= 1.5.3, ==1.*",
    "pandapower >= 2.14.4, ==2.*",
    "numpy >= 1.26.4, ==1.*",
    "gymnasium >= 0.28.1, ==0.*",
    "shapely >= 2.0.6, ==2.*"
]
requires-python = ">=3.11"